### ISSUE TITLE
"Cannot parse"

### ISSUE THREAD

**Issue by LeeUnd** [MichaelTunnell/ego-zip-downloads-userscript#1]
I am running Ubuntu 14.04, Firefox 52. I have installed the Greasemoney extension. However, when I try to install your EGO userscript (from either location) I get an error message:

`Download Error

Could not parse script:
Ignoring @match pattern https://extensions.gnome.org because
Error @match: Could not parse the pattern.`

Any idea of how to fix?

**Comment by MichaelTunnell** [comment]
Quick question before testing, you mean Ubuntu GNOME 14.04 right?

**Comment by LeeUnd** [comment]
Yes, that's right. Using GNOME v. 3.10.4.

**Comment by LeeUnd** [comment]
Thanks, Michael. Works great! Great fast service!

**Comment by MichaelTunnell** [comment]
This bug report actually made me find another bug which then made me redesign the whole thing so that it blended better with the latest version of the EGO website.

So instead of just releasing 1.1, it's now 2.0. :)

Anyway, thanks for the report.

**Comment by LeeUnd** [comment]
Great! Worked out for both of us.
